name: JumpTask Token Prod

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"  # roda a cada 5 minutos

jobs:
  get_token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install requests pynacl

      - name: Get Access Token and Save Secrets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          GOOGLE_ID_TOKEN: ${{ secrets.GOOGLE_ID_TOKEN }}
        run: python get_access_token_prod.py

  use_token:
    needs: get_token
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Access Token
        run: |
          echo "Access token válido: ${{ secrets.ACCESS_TOKEN }}"
          curl -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" https://api.jumptask.io/some_endpoint
