name: JumpTask Token Full Automatic Debug

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # roda todo dia à meia-noite

jobs:
  get_token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install requests pynacl

      - name: Get Access Token
        id: token
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}  # opcional, pode estar vazio
        run: |
          ACCESS_TOKEN=$(python get_access_token_auto_debug.py | grep 'ACCESS_TOKEN=' | cut -d '=' -f2)
          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Use Access Token
        run: |
          echo "Access token válido: $ACCESS_TOKEN"
          curl -H "Authorization: Bearer $ACCESS_TOKEN" https://api.jumptask.io/some_endpoint
