name: JumpTask Token Full Automatic Debug

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # roda todo dia à meia-noite

jobs:
  get_token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install requests pynacl

      - name: Renovar Access Token se necessário
        env:
          URL_API: ${{ secrets.URL_API }}
          TOKEN: ${{ secrets.TOKEN }}          # Google ID Token
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python renovar_token.py

      - name: Usar Access Token
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          curl -H "Authorization: Bearer $ACCESS_TOKEN" https://api.jumptask.io/accounting/balances
